[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  
[dev]
  framework = "vite"
  targerPorta = 8081

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
